# Generated by Django 5.0.3 on 2024-04-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kltngvhuongdan',
            name='gv_huong_dan',
        ),
        migrations.AddField(
            model_name='kltngvhuongdan',
            name='gv_huong_dan',
            field=models.ManyToManyField(blank=True, default=1, to='theses.giangvien'),
        ),
    ]
