# Generated by Django 5.0.3 on 2024-04-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_remove_kltngvhuongdan_gv_huong_dan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diem',
            name='tieu_chi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theses.tieuchi'),
        ),
        migrations.AlterField(
            model_name='tieuchi',
            name='kltn',
            field=models.ManyToManyField(blank=True, related_name='tieu_chi', to='theses.khoaluantotnghiep'),
        ),
    ]
