# Generated by Django 5.0.3 on 2024-04-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_alter_diem_tieu_chi_alter_tieuchi_kltn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kltngvhuongdan',
            name='gv_huong_dan',
            field=models.ManyToManyField(blank=True, to='theses.giangvien'),
        ),
    ]
