# Generated by Django 5.0.3 on 2024-05-21 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_alter_khoaluantotnghiep_diem_tong'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='khoaluantotnghiep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='khoaluantotnghiep',
            name='hdbvkl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='theses.hoidongbvkl'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='khoaluantotnghiep',
            name='mssv',
        ),
        migrations.AddField(
            model_name='khoaluantotnghiep',
            name='mssv',
            field=models.ManyToManyField(to='theses.sinhvien'),
        ),
    ]
