# Generated by Django 5.0.3 on 2024-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_alter_khoaluantotnghiep_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoaluantotnghiep',
            name='gv_huong_dan',
            field=models.ManyToManyField(to='theses.giangvien'),
        ),
    ]
