# Generated by Django 5.0.3 on 2024-05-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_khoaluantotnghiep_gv_huong_dan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khoaluantotnghiep',
            name='gv_huong_dan',
        ),
    ]
