# Generated by Django 5.0.4 on 2024-04-10 10:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoiDongBVKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ngay_bao_ve', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ten_lop', models.CharField(max_length=100)),
                ('si_so', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NghanhHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('ten_nganh', models.CharField(max_length=100)),
                ('so_tin_chi', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(default='static/graduatethesis/defaultavatar.jpg', upload_to='graduatethesis/%Y/%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('bang_cap', models.CharField(max_length=100)),
                ('kinh_nghiem', models.CharField(max_length=255)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiaoVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('trinh_do', models.CharField(max_length=100)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KhoaLuanTotNghiep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('ten_khoa_luan', models.CharField(max_length=200)),
                ('ty_le_dao_van', models.FloatField()),
                ('diem_tong', models.FloatField()),
                ('id_gv_phan_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KLTNGVHuongDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('id_gv_huong_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
                ('id_kltn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.khoaluantotnghiep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LopHocNghanhHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.lop')),
                ('nghanh_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.nghanhhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('mssv', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nam_nhap_hoc', models.IntegerField()),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graduatethesis.lop')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='khoaluantotnghiep',
            name='mssv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.sinhvien'),
        ),
        migrations.CreateModel(
            name='TieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('tieu_chi', models.CharField(max_length=200)),
                ('ty_le', models.FloatField()),
                ('id_kltn', models.ManyToManyField(blank=True, to='graduatethesis.khoaluantotnghiep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('vai_tro', models.IntegerField(choices=[(1, 'CHU_TICH'), (2, 'THU_KY'), (3, 'THANH_VIEN')])),
                ('id_gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
                ('id_hdbvkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.hoidongbvkl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('tieu_chi', models.CharField(max_length=200)),
                ('diem', models.FloatField()),
                ('id_gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
                ('id_kltn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.khoaluantotnghiep')),
            ],
            options={
                'unique_together': {('tieu_chi', 'id_gv', 'id_kltn')},
            },
        ),
    ]
