# Generated by Django 5.0.4 on 2024-04-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduatethesis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LopHocMonHoc',
            new_name='LopHocNghanhHoc',
        ),
    ]
