# Generated by Django 5.0.4 on 2024-04-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduatethesis', '0002_rename_lophocmonhoc_lophocnghanhhoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoiDongBVKL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ngay_bao_ve', models.DateField()),
                ('tinh_trang', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KhoaLuanTotNghiep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ten_khoa_luan', models.CharField(max_length=200)),
                ('ty_le_dao_van', models.FloatField()),
                ('diem_tong', models.FloatField()),
                ('id_gv_phan_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
                ('mssv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.sinhvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tieu_chi', models.CharField(max_length=200)),
                ('diem', models.FloatField()),
                ('id_gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
                ('id_kltn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.khoaluantotnghiep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KLTNGVHuongDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id_gv_huong_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
                ('id_kltn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.khoaluantotnghiep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tieu_chi', models.CharField(max_length=200)),
                ('ty_le', models.FloatField()),
                ('id_kltn', models.ManyToManyField(blank=True, null=True, to='graduatethesis.khoaluantotnghiep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('vai_tro', models.CharField(choices=[(1, 'CHU_TICH'), (2, 'THU_KY'), (3, 'THANH_VIEN')], max_length=100)),
                ('id_gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.giangvien')),
                ('id_kltn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduatethesis.khoaluantotnghiep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GiaoVien',
        ),
    ]
