# Generated by Django 5.0.4 on 2024-04-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduatethesis', '0003_hoidongbvkl_khoaluantotnghiep_diem_kltngvhuongdan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieuchi',
            name='id_kltn',
            field=models.ManyToManyField(blank=True, to='graduatethesis.khoaluantotnghiep'),
        ),
    ]
